src/Entity/Region.php
<?php

namespace App\Entity;

use App\Repository\RegionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RegionRepository::class)
 */
class Region
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $RegionName;

    /**
     * @ORM\OneToMany(targetEntity=Product::class, mappedBy="region")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRegionName(): ?string
    {
        return $this->RegionName;
    }

    public function setRegionName(string $RegionName): self
    {
        $this->RegionName = $RegionName;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setRegion($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getRegion() === $this) {
                $product->setRegion(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return  $this->RegionName;
    }
}

src/Form/RegionType.php
<?php

namespace App\Form;

use App\Entity\Region;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RegionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('RegionName', TextType::class,[
                'label' => 'Région:'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Region::class,
        ]);
    }
}

src/Controller/RegionController.php
<?php

namespace App\Controller;

use App\Entity\Region;
use App\Form\RegionType;
use App\Repository\RegionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/region')]
class RegionController extends AbstractController
{
    #[Route('/', name: 'region_index', methods: ['GET'])]
    public function index(RegionRepository $regionRepository): Response
    {
        return $this->render('region/index.html.twig', [
            'regions' => $regionRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'region_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $region = new Region();
        $form = $this->createForm(RegionType::class, $region);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($region);
            $entityManager->flush();

            return $this->redirectToRoute('region_index');
        }

        return $this->render('region/new.html.twig', [
            'region' => $region,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'region_show', methods: ['GET'])]
    public function show(Region $region): Response
    {
        return $this->render('region/show.html.twig', [
            'region' => $region,
        ]);
    }

    #[Route('/{id}/edit', name: 'region_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Region $region): Response
    {
        $form = $this->createForm(RegionType::class, $region);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('region_index');
        }

        return $this->render('region/edit.html.twig', [
            'region' => $region,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'region_delete', methods: ['POST'])]
    public function delete(Request $request, Region $region): Response
    {
        if ($this->isCsrfTokenValid('delete'.$region->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($region);
            $entityManager->flush();
        }

        return $this->redirectToRoute('region_index');
    }
}

templates/region/_delete_form.html.twig
<form method="post" action="{{ path('region_delete', {'id': region.id}) }}" onsubmit="return confirm('Voulez vraiment supprimer cette région?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ region.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/region/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn btn-success">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/region/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Éditer une Region{% endblock %}

{% block body %}
    <h1 class="text-center m-3">Éditer une Region</h1>

    {{ include('region/_form.html.twig', {'button_label': 'Éditer'}) }}

    <a href="{{ path('region_index') }}"class="btn btn-primary">Retour</a>

    {{ include('region/_delete_form.html.twig') }}
{% endblock %}

templates/region/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Régions{% endblock %}

{% block body %}
    <h1 class="text-center m-3">Régions</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Régions</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for region in regions %}
            <tr>
                <td>{{ region.id }}</td>
                <td>{{ region.regionName }}</td>
                <td>
                    {# <a href="{{ path('region_show', {'id': region.id}) }}">Voir</a> #}
                    <a href="{{ path('region_edit', {'id': region.id}) }}" class="btn btn-outline-warning">Éditer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('region_new') }}" class="btn btn-primary">Creér une nouvelle région</a>
{% endblock %}

templates/region/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Région{% endblock %}

{% block body %}
    <h1 class="text-center m-3">Créer une nouvelle Région</h1>

    {{ include('region/_form.html.twig') }}

    <a href="{{ path('region_index') }}" class="btn btn-primary">Retour</a>
{% endblock %}

templates/region/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Région{% endblock %}

{% block body %}
    <h1>Région</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ region.id }}</td>
        </tr>
        <tr>
            <th>Région</th>
            <td>{{ region.regionName }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('region_index') }}" class="btn btn-primary">Retour</a>

    <a href="{{ path('region_edit', {'id': region.id}) }}"class="btn btn-warning">Éditer</a>

    {{ include('region/_delete_form.html.twig') }}
{% endblock %}